// <auto-generated />
namespace JewelryStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ProductionEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductionEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "202002221622074_ProductionEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
